dist: xenial  # py37, cf. https://github.com/travis-ci/travis-ci/issues/9815
sudo: yes     # py37, cf. https://github.com/travis-ci/travis-ci/issues/9815
language: python
python:
  - "3.7"
install:
  - pip install virtualenv https://github.com/airspeed-velocity/asv/archive/master.tar.gz
  - cp .ci/.asv-machine.json ~
script:
  - .ci/run_ci.sh
notifications:
  email: false
